rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/config/routes.rb
Refinery::Application.routes.draw do
  get '/contact', :to => 'inquiries#new', :as => 'new_inquiry'
  resources :contact, :as => :inquiries, :controller => 'inquiries' do
    collection do
      get :thank_you
    end
  end

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :inquiries do
      collection do
        get :spam
      end
      member do
        get :toggle_spam
      end
    end
    resources :inquiry_settings
  end
end

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/models/inquiry.rb
class Inquiry < ActiveRecord::Base

  filters_spam :message_field => :message,
               :email_field => :email,
               :author_field => :name,
               :other_fields => [:phone],
               :extra_spam_words => %w()

  validates :name, :presence => true
  validates :message, :presence => true
  validates :email, :format=> { :with =>  /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }

  acts_as_indexed :fields => [:name, :email, :message, :phone]

  scope :newest, :order => 'created_at DESC'

  def self.latest(number = 7, include_spam = false)
    unless include_spam
      ham.find(:all, :limit => number)
    else
      newest.find(:all, :limit => number)
    end
  end

end

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/models/inquiry_setting.rb
class InquirySetting < ActiveRecord::Base

  def self.confirmation_body
    RefinerySetting.find_or_set(:inquiry_confirmation_body,
      "Thank you for your inquiry %name%,\n\nThis email is a receipt to confirm we have received your inquiry and we'll be in touch shortly.\n\nThanks."
    )
  end

  def self.confirmation_subject
    RefinerySetting.find_or_set(:inquiry_confirmation_subject,
                                "Thank you for your inquiry")
  end

  def self.confirmation_subject=(value)
    RefinerySetting[:inquiry_confirmation_subject] = value
  end

  def self.notification_recipients
    RefinerySetting.find_or_set(:inquiry_notification_recipients,
                                (defined?(Role) ? Role[:refinery].users.first.email : '' rescue ''))
  end

  def self.notification_subject
    RefinerySetting.find_or_set(:inquiry_notification_subject,
                                "New inquiry from your website")
  end

end

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/controllers/admin/inquiries_controller.rb
class Admin::InquiriesController < Admin::BaseController

  crudify :inquiry, :title_attribute => "name", :order => "created_at DESC"

  before_filter :get_spam_count, :only => [:index, :spam]

  def index
    @inquiries = Inquiry.ham.with_query(params[:search]) if searching?

    @grouped_inquiries = group_by_date(Inquiry.ham)
  end

  def spam
    @inquiries = Inquiry.spam.with_query(params[:search]) if searching?

    @grouped_inquiries = group_by_date(Inquiry.spam)
  end

  def toggle_spam
    find_inquiry
    @inquiry.toggle!(:spam)

    redirect_to :back
  end

protected

  def get_spam_count
    @spam_count = Inquiry.count(:conditions => {:spam => true})
  end

end

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/controllers/admin/inquiry_settings_controller.rb
class Admin::InquirySettingsController < Admin::BaseController

  crudify :refinery_setting,
          :title_attribute => "name",
          :order => 'name ASC',
          :redirect_to_url => "admin_inquiries_url"

  before_filter :redirect_back_to_inquiries?, :only => [:index]
  before_filter :set_url_override?, :only => [:edit, :update]
  after_filter :save_subject_for_confirmation?, :only => [:create, :update]
  around_filter :rewrite_flash?, :only => [:create, :update]

protected
  def rewrite_flash?
    yield

    flash[:notice] = flash[:notice].to_s.gsub(/(\'.*\')/) {|m| m.titleize}.gsub('Inquiry ', '')
  end

  def save_subject_for_confirmation?
    InquirySetting.confirmation_subject = params[:subject] if params.keys.include?('subject')
  end

  def redirect_back_to_inquiries?
    redirect_to admin_inquiries_url
  end

  def set_url_override?
    @url_override = admin_inquiry_setting_url(@refinery_setting, :dialog => from_dialog?)
  end

  def find_refinery_setting
    # ensure that we're dealing with the name of the setting, not the id.
    begin
      if params[:id].to_i.to_s == params[:id]
        params[:id] = RefinerySetting.find(params[:id]).name.to_s
      end
    rescue
    end

    # prime the setting first, if it's valid.
    if InquirySetting.methods.map(&:to_sym).include?(params[:id].to_s.gsub('inquiry_', '').to_sym)
      InquirySetting.send(params[:id].to_s.gsub('inquiry_', '').to_sym)
    end
    @refinery_setting = RefinerySetting.find_by_name(params[:id])
  end

end

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController

  before_filter :find_page, :only => [:create, :new]

  def index
    redirect_to :action => "new"
  end

  def thank_you
    @page = Page.find_by_link_url("/contact/thank_you", :include => [:parts, :slugs])
  end

  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(params[:inquiry])

    if @inquiry.save
      if @inquiry.ham?
        begin
          InquiryMailer.notification(@inquiry, request).deliver
        rescue
          logger.warn "There was an error delivering an inquiry notification.\n#{$!}\n"
        end

        begin
          InquiryMailer.confirmation(@inquiry, request).deliver
        rescue
          logger.warn "There was an error delivering an inquiry confirmation:\n#{$!}\n"
        end
      end

      redirect_to thank_you_inquiries_url
    else
      render :action => 'new'
    end
  end

protected

  def find_page
    @page = Page.find_by_link_url('/contact', :include => [:parts, :slugs])
  end

end

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/helpers/inquiries_helper.rb
module InquiriesHelper
end

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/views/admin/inquiries/_inquiry.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>'>
  <span class='title'>
    <%= link_to inquiry.name, admin_inquiry_url(inquiry) %> <%= t('.said') %>
    <span class="preview"><%= truncate(strip_tags(inquiry.message), :length => 60) -%></span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag('delete.png'), admin_inquiry_url(inquiry),
                :class => "cancel confirm-delete",
                :title => t('admin.inquiries.delete'),
                :'data-confirm' => t('shared.admin.delete.message', :title => inquiry.name),
                :'data-method' => "delete" -%>

    <%= link_to refinery_icon_tag('zoom.png'), admin_inquiry_url(inquiry),
                :title => t('.read_inquiry') -%>

    <% if inquiry.spam? %>
      <%= link_to refinery_icon_tag('email.png'), toggle_spam_admin_inquiry_url(inquiry),
                  :title => t('.mark_as_ham') -%>
    <% else %>
      <%= link_to refinery_icon_tag('bin_closed.png'), toggle_spam_admin_inquiry_url(inquiry),
                  :title => t('.mark_as_spam') -%>
    <% end %>
  </span>
</li>

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/views/admin/inquiries/_submenu.html.erb
<div id='actions'>
  <ul>
    <li>
      <%= render :partial => "/shared/admin/search", :locals => {:url => request.path} %>
    </li>
    <li <%= "class='selected'" if params[:action] == "index" %>>
      <%= link_to t('.inbox'), admin_inquiries_url, :class => "email_icon" %>
    </li>
    <li <%= "class='selected'" if params[:action] == "spam" %>>
      <% if @spam_count > 0  %>
        <%= link_to "#{t('.spam')} (#{@spam_count})", spam_admin_inquiries_url, :class => "spam_icon" %>
      <% else %>
        <%= link_to t('.spam'), spam_admin_inquiries_url, :class => "spam_empty_icon" %>
      <% end %>
    </li>
    <li>
      <%= link_to t('.update_notified'),
                    edit_admin_inquiry_setting_url(:inquiry_notification_recipients, :dialog => true, :height => 300),
                    :class => "user_comment_icon" %>
    </li>
    <li>
      <%= link_to t('.edit_confirmation_email'),
                  edit_admin_inquiry_setting_url(:inquiry_confirmation_body, :dialog => true),
                  :class => "edit_email_icon" %>
    </li>
  </ul>
</div>

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/views/admin/inquiries/index.html.erb
<%= render :partial => "submenu" %>
<div id='records'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
    <% if @inquiries.any? %>
      <ul>
        <%= render :partial => "inquiry", :collection => @inquiries %>
      </ul>
    <% else %>
      <p><%= t('shared.admin.search.no_results') %></p>
    <% end %>
  <% else %>
    <% if @grouped_inquiries.any? -%>
      <% @grouped_inquiries.each do |container| %>
        <h3><%= l((inquiry_group = container.last).first.created_at) %></h3>
        <ul>
          <%= render :partial => 'inquiry', :collection => inquiry_group %>
        </ul>
      <% end %>
    <% else -%>
      <p>
        <strong><%= t('.no_inquiries') %></strong>
      </p>
    <% end -%>
  <% end %>
</div>

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/views/admin/inquiries/show.html.erb
<div id='actions'>
  <h2><%= t('.details')%></h2>
  <p>
    <strong><%= t('.age') %>:</strong> <%= time_ago_in_words(@inquiry.created_at) %>
  </p>
  <% if @inquiry.spam? %>
    <p>
      <strong><%= t('.spam') %>:</strong> <%= t('.spam_yes') %>
    </p>
  <% end %>
  <h2><%= t('.actions') %></h2>
  <ul>
    <li>
      <%= link_to t('.back_to_all_inquiries'), {:action => 'index'}, :class => "back_icon" %>
    </li>
    <li>
      <%= link_to t('admin.inquiries.delete'),
                  admin_inquiry_url(@inquiry),
                  :class => 'delete_icon no-tooltip confirm-delete',
                  :title => t('admin.inquiries.delete'),
                  :'data-confirm' => t('shared.admin.delete.message', :title => @inquiry.name),
                  :'data-method' => "delete" %>
    </li>
  </ul>
</div>
<div id='records'>
  <h2><%= t('.inquiry') %></h2>
  <table id='inquiry'>
    <tr>
      <td>
        <strong><%= t('.to') %></strong>
      </td>
      <td>
        <%= RefinerySetting[:site_name] %>
      </td>
    </tr>
    <tr>
      <td>
        <strong><%= t('.from') %></strong>
      </td>
      <td>
        <%= @inquiry.name %> [<%= mail_to @inquiry.email, @inquiry.email, {:title => t('.click_to_email')} %>]
      </td>
    </tr>
    <% unless @inquiry.phone.blank? %>
      <tr>
        <td>
          <strong><%= t('.phone') %></strong>
        </td>
        <td>
          <%= @inquiry.phone %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td>
        <strong><%= t('.date') %></strong>
      </td>
      <td>
        <%= l(Date.parse(@inquiry.created_at.to_s), :format => :long) %>
      </td>
    </tr>
    <tr>
      <td valign='top'>
        <strong><%= t('.message') %></strong>
      </td>
      <td>
        <p style='margin-top: 0px'>
          <%= @inquiry.message.gsub("\r\n\r\n", "\r\n").gsub("\r\n", "</p><p>") %>
        </p>
      </td>
    </tr>
  </table>
</div>

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/views/admin/inquiries/spam.html.erb
<%= render :partial => "submenu" %>
<div id='records'>
  <% if searching? %>
    <h2><%= t('shared.admin.search.results_for', :query => params[:search]) %></h2>
    <% if @inquiries.any? %>
      <ul>
        <%= render :partial => "inquiry", :collection => @inquiries %>
      </ul>
    <% else %>
      <p><%= t('shared.admin.search.no_results') %></p>
    <% end %>
  <% else %>
    <% if @grouped_inquiries.any? -%>
      <% @grouped_inquiries.each do |container| %>
        <h3><%= l((inquiry_group = container.last).first.created_at) %></h3>
        <ul>
          <%= render :partial => 'inquiry', :collection => inquiry_group %>
        </ul>
      <% end %>
    <% else -%>
      <p>
        <strong><%= t('.no_spam') %></strong>
      </p>
    <% end -%>
  <% end %>
</div>

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/views/admin/inquiry_settings/_confirmation_email_form.html.erb
<%= form_for([:admin, @refinery_setting], :url => (@url_override || @url)) do |f| %>

  <p>
    <%= t('.explanation') %>
  </p>
  <p>
    <%= t('.below_edit_email_sent') %>
  </p>
  <table id='inquiry'>
    <tr>
      <td>
        <label class='stripped'><%= t('.to') %></label>
      </td>
      <td>
        <%= t('.the_customer_making_inquiry') %>
      </td>
    </tr>
    <tr>
      <td>
        <label class='stripped'><%= t('.from') %></label>
      </td>
      <td>
        <%= "#{RefinerySetting[:site_name]} &lt;no-reply@#{request.domain(RefinerySetting.find_or_set(:tld_length, 1))}&gt;".html_safe %>
      </td>
    </tr>
    <tr>
      <td>
        <label class='stripped'><%= t('.subject') %></label>
      </td>
      <td>
        <%= text_field_tag 'subject', InquirySetting.confirmation_subject,
                           :class => 'widest' %>
      </td>
    </tr>
    <tr>
      <td valign='top'>
        <%= f.label :value, t('.message'),
                    :class => 'stripped' %>
      </td>
      <td>
        <%= f.text_area :value,
                        :rows => "5",
                        :class => 'widest' %>
        <br/>
        <em><%= t('.note') %></em>
      </td>
    </tr>
  </table>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => false,
               :cancel_url => admin_inquiries_url,
               :hide_delete => true
             } %>
<% end %>

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/views/admin/inquiry_settings/_notification_recipients_form.html.erb
<%= form_for([:admin, @refinery_setting], :url => (@url_override || @url)) do |f| %>

  <div class='field'>
    <span class='label_with_help'>
      <%= f.label :value, t('.inquiry_settings_value_name') %>
    </span>
    <%= f.text_field :value, :class => "larger widest" %>
  </div>

  <p>
    <%= t('.hint') %>
  </p>
  <p>
    <%= t('.example') %>
  </p>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => false,
               :cancel_url => admin_inquiries_url,
               :hide_delete => true
             } %>
<% end %>

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/views/admin/inquiry_settings/edit.html.erb
<% if @refinery_setting.name.to_s.titleize == "Inquiry Notification Recipients" %>
  <%= render :partial => "notification_recipients_form", :locals => {:edit => true} -%>
<% else %>
  <%= render :partial => "confirmation_email_form", :locals => {:edit => true} -%>
<% end %>

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/views/inquiries/new.html.erb
<% content_for :body_content_left do %>
  <div class='inquiries'>
    <%=raw @page[Page.default_parts.first.to_sym] %>

    <%= form_for @inquiry do |f| %>
      <%= render :partial => "/shared/admin/error_messages",
                 :locals => {
                   :object => @inquiry,
                   :include_object_name => true
                 } %>
      <div class='field'>
        <%= f.required_label :name %>
        <%= f.text_field :name %>
      </div>
      <div class='field'>
        <%= f.required_label :email %>
        <%= f.text_field :email %>
      </div>
      <div class='field'>
        <%= f.label :phone %>
        <%= f.text_field :phone %>
      </div>
      <div class='field message_field'>
        <%= f.required_label :message  %>
        <%= f.text_area :message, :rows => 8 %>
      </div>
      <div class='actions'>
        <%= f.submit t('.send') %>
        <%= link_to t('.privacy_policy'), "/pages/privacy-policy", :id => "privacy_link" if RefinerySetting.find_or_set(:show_contact_privacy_link, false) %>
      </div>
    <% end %>
  </div>
<% end %>
<%= render :partial => "/shared/content_page" %>

rmagick/ruby/1.8/gems/refinerycms-inquiries-0.9.8.4/app/views/inquiries/thank_you.html.erb
<%= render :partial => "/shared/content_page" %>